Timerecordd
FITTY-APP/Fitty-Frontend-App pull request #30
Opened 2023-08-26 13:47 UTC by JJolggit

2023-08-26 16:01 UTC, dicohy27 requested changes
운동 시작 종료 버튼 문제 해결하셈

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/page/calendar_menu/tab/my_exercise_calendar_tab.dart
> +          // ),
뭐여이건

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/page/calendar_menu/tab/my_exercise_calendar_tab.dart
> +// late starTime 값이 받아지기 전까지 widget 불러오기가 안됨//
해결아직안됐다는뜻임?

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/page/exercise/daily_routine_page.dart
> +  int istimeGo = 0;
isTimeGo로 고치셈

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/page/exercise/daily_routine_page.dart
> +                        },
이 부분 로직이 이상함. 그리고 istimeGo가 짝수인지 홀수인지로 운동 중 여부 판단하는게 안좋아보임. 만약 버튼을 4번 누르면 endTime이 다시 기록되잖음 근데 5번째 눌렀을땐 또 아무 반응 없다가 다시 6번째 누르면 그때 endTime이 또 기록되잖아. 잘못된 코드임.
그리고 setState함수 안에서 istimeGo같은 변수 업데이트 처리하셈. 저거 밖에서 처리하는 것도 코드 안이쁨

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/page/exercise/daily_routine_page.dart
> +                                      content: '',
얜 뭐냐?

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/page/exercise/exercise_list_page.dart
> +String searchText = '';
얘는 아래 state클래스(```_ExerciseListPageState```)안에 들어가는게 맞아 보임. 전역 변수로 쓸 애는 아닌거같음

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/page/exercise/exercise_list_page.dart
> +                        !_exercises[index].contains(searchText.toLowerCase())) {
한글만 입력하는데 ```toLowerCase```는 왜쓴거임?

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/widget/exercise/one_exercise_record_summary_widget.dart
> +        Provider.of<AllExerciseRecord>(context, listen: false)
```Provider.of``` 말고 ```context.read``` 얘 쓰는거 추천함 왜냐면 listen 기본값이 true라서 위젯 업데이트 안하려면 false로 지정해줘야되는데 context.read는 그럴 필요 없음

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/widget/exercise/one_exercise_record_summary_widget.dart
> +    var selectedDayExerciseRecord =
안쓰는 변수는 코드에 남겨두지 말고 삭제하셈

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/widget/exercise/one_exercise_record_summary_widget.dart
> +                width: 100,
이건 왜 줄임?

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/widget/exercise/one_exercise_record_summary_widget.dart
> +            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
이건 왜바꿈

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/widget/exercise/time_record_widget.dart
> +        Provider.of<AllExerciseRecord>(context, listen: false)
얘도 마찬가지

2023-08-26 16:01 UTC, dicohy27 commented on fitty_frontend_app/lib/widget/exercise/time_record_widget.dart
> +            .getDayExerciseRecord(DateTime.now());
DateTime.now 집어넣은건 아직 안바꾼거임? 이러면 항상 오늘 날짜만 불러오잖음

2023-08-26 16:01 UTC, dicohy27 requested changes
운동 시작 종료 버튼 문제 해결하셈

2023-08-26 16:47 UTC, JJolggit commented on fitty_frontend_app/lib/page/calendar_menu/tab/my_exercise_calendar_tab.dart
> +// late starTime 값이 받아지기 전까지 widget 불러오기가 안됨//
ㅇㅇ. late으로 써가지고 저기 값이 들어가기 전까지 index값이 없어서 오류남

2023-08-26 17:01 UTC, JJolggit commented on fitty_frontend_app/lib/page/calendar_menu/tab/my_exercise_calendar_tab.dart
> +          // ),
네비게이터 운동탭에 시간 기록하는 위젯 빌드

2023-08-26 17:03 UTC, JJolggit commented on fitty_frontend_app/lib/page/exercise/daily_routine_page.dart
> +                        },
니가 뭘알아!!!!!

2023-08-26 17:06 UTC, dicohy27 commented on fitty_frontend_app/lib/page/calendar_menu/tab/my_exercise_calendar_tab.dart
> +          // ),
왜주석친거

2023-08-26 17:07 UTC, dicohy27 commented on fitty_frontend_app/lib/page/exercise/daily_routine_page.dart
> +                        },
조빱련ㅋ

2023-08-26 17:08 UTC, JJolggit commented on fitty_frontend_app/lib/page/calendar_menu/tab/my_exercise_calendar_tab.dart
> +          // ),
74번째 줄에서 오류남. startTime에 값 들어가기 전까지
index out of range로 빌드가 안댐

2023-08-28 08:19 UTC, dicohy27 commented on fitty_frontend_app/lib/widget/exercise/one_exercise_record_summary_widget.dart
> +                width: 100,
걍 다시 돌려놓음 텍스트 잘려서 다음 줄로 내려감

2023-08-28 08:22 UTC, dicohy27 commented on fitty_frontend_app/lib/widget/exercise/one_exercise_record_summary_widget.dart
> +            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
얜 걍 다시 돌려놓음 텍스트 잘려서 다음 줄로 넘어가버림

2023-08-28 08:22 UTC, dicohy27 approved these changes

2023-08-28 08:23 UTC, dicohy27 commented
코드 약간 수정해서 커밋했음

2023-08-28 08:38 UTC, dicohy27 commented on fitty_frontend_app/lib/widget/exercise/one_exercise_record_summary_widget.dart
> +            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
test

2023-08-28 08:41 UTC, dicohy27 commented on fitty_frontend_app/lib/widget/exercise/one_exercise_record_summary_widget.dart
> +                width: 150,
텍스느 짤려서 크기 다시 되돌림

2023-08-28 12:04 UTC, merged