Feat/signup login
FITTY-APP/Fitty-Frontend-App pull request #38
Opened 2023-09-05 05:58 UTC by dicohy27

로그인, 회원가입 기능 구현 완료

2023-09-05 06:00 UTC, dicohy27 commented on lib/api/api.dart
>    static const validateEmail = "$hostConnect/user/validate_email.php";
얘넨 이제 안쓸듯

2023-09-05 06:02 UTC, dicohy27 commented on lib/page/login_signup/login_page.dart
> +    // todo : userInfo 검증 필요
@uuccu 지금은 그냥 userInfo가 존재하면 바로 로그인 페이지 나가게(MenuRoutingPage로 이동)되어있는데 이걸 이제 jwt토큰을 서버에 보내서 검증 받는 식으로 해야되냐?

2023-09-05 06:39 UTC, uuccu commented on lib/page/login_signup/login_page.dart
> +    // todo : userInfo 검증 필요
음 그거보다 바로 MenuRoutingPage로 들어가는데에 필요한 API에서 토큰 verifying 에러가 발생하면 로그인페이지로 가게 하는게 나을듯

2023-09-05 06:39 UTC, uuccu commented on lib/api/api.dart
>    static const validateEmail = "$hostConnect/user/validate_email.php";
안물안궁

2023-09-05 06:40 UTC, dicohy27 commented on lib/api/api.dart
>    static const validateEmail = "$hostConnect/user/validate_email.php";
아가리해

2023-09-05 06:41 UTC, dicohy27 commented on lib/page/login_signup/login_page.dart
> +    // todo : userInfo 검증 필요
토큰 verifying 에러는 서버에서 보내줌?

2023-09-06 03:17 UTC, uuccu commented on lib/page/login_signup/login_page.dart
> +    // todo : userInfo 검증 필요
ㅇㅇ

2023-09-06 07:57 UTC, uuccu commented
스샷왜 안올리냐

2023-09-06 07:58 UTC, uuccu commented
아니 움짤

2023-09-06 08:01 UTC, dicohy27 commented
옹량맞추기 짜증남

2023-09-06 13:31 UTC, dicohy27 commented
https://github.com/FITTI-APP/Fitti-Frontend-App/assets/59111693/01c641f5-a57e-432c-8286-8038e339ada3

2023-09-06 14:24 UTC, uuccu requested changes
고생했음. 
근데 storage에 저장하는 코드는 어디에 있냐? 보이지가 않는데

2023-09-06 14:24 UTC, uuccu commented on README.md
> +
??

2023-09-06 14:24 UTC, uuccu commented on lib/api/api.dart
>  }
음.... //todo profile이라고 주석처리점

2023-09-06 14:24 UTC, uuccu commented on lib/data/auth_service.dart
> +
Listner쓴거같은데 어떨때를 위한애임?

2023-09-06 14:24 UTC, uuccu commented on lib/data/auth_service.dart
> +  }
try catch문을 왜 이렇게 작성한거임?

2023-09-06 14:24 UTC, uuccu commented on lib/data/auth_service.dart
> +      if (response.statusCode == 200) {
이렇게 api 호출하는군요

2023-09-06 14:24 UTC, uuccu commented on lib/main.dart
> +          }
key을 이거 하나로만 저장할거면 상수로쓰고. key값을 겹치지 않게 해야할듯. 앱깔고 계정 2개로 로그인왔다갔다가 안된다는거니까

2023-09-06 14:24 UTC, uuccu commented on lib/page/diet/food_amount_input_page.dart
> +              controller: foodAmountController,
? 로그인만 만든게 아니네 ㅅㅂ 어쩐지 이상하더라

2023-09-06 14:24 UTC, uuccu commented on lib/page/menu_routing_page.dart
> +                        }
logout 버튼도 만들었냐? 굳굳 대단하네.

2023-09-06 14:25 UTC, uuccu commented on lib/data/auth_service.dart
> +      if (response.statusCode == 200) {
근데 왜 dio라는 객체를 통해서 접근하는거임?

2023-09-06 14:26 UTC, dicohy27 commented on README.md
> +
뭐말하는지모를까봐 이미지 첨부함

2023-09-06 14:26 UTC, dicohy27 commented on lib/data/auth_service.dart
> +
쟤 쓰면 Consumer로 감싼 애들 ui가 리로드됨

2023-09-06 14:27 UTC, dicohy27 commented on lib/data/auth_service.dart
> +  }
어디가 이상한거임? 코파일럿이 만들어준거 약간 수정한건데

2023-09-06 14:30 UTC, dicohy27 commented on lib/data/auth_service.dart
> +      if (response.statusCode == 200) {
ㅇㅇ

2023-09-06 14:30 UTC, dicohy27 commented on lib/page/diet/food_amount_input_page.dart
> +              controller: foodAmountController,
뭐가

2023-09-06 14:30 UTC, dicohy27 commented on lib/page/menu_routing_page.dart
> +                        }
ㅇㅇ

2023-09-06 14:33 UTC, dicohy27 commented on lib/api/api.dart
>  }
함

2023-09-06 14:34 UTC, dicohy27 commented
> 고생했음. 근데 storage에 저장하는 코드는 어디에 있냐? 보이지가 않는데

무슨 storage 말하는거임 운동정보 아님 로그인정보?

2023-09-06 14:36 UTC, dicohy27 commented on lib/main.dart
> +          }
상수로 바꿀거긴 한데 계정 2개 자동 로그인 정보를 저장할 필요는 없지 않음? 하나 로그아웃 하고 다른 계정으로 로그인 하려면 어차피 이메일 비번 입력해야되니까

2023-09-07 05:01 UTC, uuccu commented
> 

로그인 토큰 저장하는 코드가 안보여서 물어본거임

2023-09-07 05:29 UTC, dicohy27 reviewed
로그인 정보 저장

2023-09-07 05:29 UTC, dicohy27 commented on lib/data/auth_service.dart
> +        onSuccess(val);
여기가 로그인 정보 저장하는 부분

2023-09-07 05:29 UTC, dicohy27 commented on lib/page/login_signup/login_page.dart
> +                          onSuccess: (val) async {
얘가 AuthService 에서의 onSuccess와 같음

2023-09-07 05:43 UTC, uuccu commented on README.md
> +
FOOK_API_KEY가 뭐임

2023-09-07 05:45 UTC, uuccu commented on lib/data/auth_service.dart
> +  }
아 어쩐지 조금 이상하더라
 try catch문 안에서 onFAIL(애가 통상적인 예외 발생 throw랑 동일하게 생각하고 말하는거임)을 쓸거면 catch에다가만 쓰는게 일반적이니까 한말이었음. try안에 onFail이 또 있으니까. 애초에 try에서 실패하면 catch로 갈탠데 try catch 쓰는의미가 좀 퇴색되는느낌.

2023-09-07 05:45 UTC, uuccu commented on lib/data/auth_service.dart
> +      if (response.statusCode == 200) {
왜 대답안하고 resolve하냐

2023-09-07 06:06 UTC, dicohy27 commented on README.md
> +
디코에 올렸잖음 고정메세지로

2023-09-07 06:08 UTC, dicohy27 commented on lib/data/auth_service.dart
> +      if (response.statusCode == 200) {
dio 질문 못봄 dio가 http 상위호환 패키지라 씀

2023-09-07 06:12 UTC, dicohy27 commented on lib/data/auth_service.dart
> +  }
try에서 실패 안했는데 회원가입이 실패하는 경우(response.statusCode가 200이 아닐 경우) try문에서 onFail 실햄됨

2023-09-07 06:14 UTC, dicohy27 commented on lib/data/auth_service.dart
> +  }
try에서 실패 안해도 회원가입 실패할 수 있잖음

2023-09-07 06:19 UTC, uuccu commented on lib/page/diet/food_amount_input_page.dart
> +              controller: foodAmountController,
식단은 분리해야지

2023-09-07 06:19 UTC, uuccu commented on lib/data/auth_service.dart
> +  }
ㅇㅇ 논리상 이상하다는게 아니고 try catch문을 개떡같이 사용했다는 의미임

2023-09-07 06:19 UTC, uuccu commented on lib/data/auth_service.dart
> +  }
걍 넘기삼

2023-09-07 06:20 UTC, uuccu commented on lib/data/auth_service.dart
> +      if (response.statusCode == 200) {
dio가 패키지임? 패키지 링크점

2023-09-07 06:20 UTC, uuccu commented on lib/main.dart
> +          }
ㅇㅇ 필요없을듯. 상수로 하삼

2023-09-07 06:21 UTC, uuccu commented on lib/data/auth_service.dart
> +        onSuccess(val);
onSuccess가 저장임?

2023-09-07 06:24 UTC, dicohy27 commented on lib/data/auth_service.dart
> +        onSuccess(val);
ㅇㅇ

2023-09-07 06:25 UTC, dicohy27 commented on lib/data/auth_service.dart
> +      if (response.statusCode == 200) {
https://pub.dev/packages/dio

2023-09-07 06:29 UTC, dicohy27 commented on lib/page/diet/food_amount_input_page.dart
> +              controller: foodAmountController,
ㅇㅇ

2023-09-07 06:39 UTC, dicohy27 commented on lib/main.dart
> +          }
완료

2023-09-08 09:34 UTC, uuccu commented on README.md
> +
그게 뭐하는 키인지 물어본거였음

2023-09-08 09:35 UTC, uuccu approved these changes

2023-09-08 09:37 UTC, merged