루틴페이지 오늘날짜 다른날짜 다르게
FITTY-APP/Fitty-Frontend-App pull request #41
Opened 2023-09-10 07:55 UTC by JJolggit

2023-09-11 09:08 UTC, dicohy27 requested changes
![image](https://github.com/FITTI-APP/Fitti-Frontend-App/assets/59111693/fb962df9-1e28-4dc0-ba4a-53f1a6095991)

출처 https://papabee.tistory.com/110

이렇게 되면 if문 조건에 따라서 아래 위젯이 생기거나 안생김

2023-09-11 09:08 UTC, dicohy27 commented on lib/page/calendar_menu/tab/my_exercise_calendar_tab.dart
> +              if (_selectedDay == DateTime.now()) {
날짜 비교를 초 단위로 비교해서 동작 안됨

2023-09-11 09:08 UTC, dicohy27 commented on lib/page/calendar_menu/tab/my_exercise_calendar_tab.dart
> +              if (_selectedDay == DateTime.now()) {
2023-09-11 00:00:00 != 2023-09-11 18:05:30

2023-09-11 09:08 UTC, dicohy27 commented on lib/page/exercise/daily_routin_page_other.dart
if문같은 조건문으로 widget생성할지 안할지 정할 수 있어서 얘 만들 필요 없음. 이 클래스 지우고 원래 DailyRoutinePage를 고치셈.

2023-09-12 23:20 UTC, JJolggit commented on lib/page/exercise/daily_routin_page_other.dart
넴

2023-11-06 15:32 UTC, uuccu commented
이건 언제끝남? 뭔지도모르겠네 컨필리트 오지게 나는중 ㅋ

2024-02-08 07:38 UTC, closed without merging